---
- name: Install OS Dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gnupg
      - golang
      - neovim
      - net-tools
      - python3-jmespath
      - python3-libcloud
      - python3-pexpect
      - python3-pip
      - python3-venv
      - python3-winrm
      - sshpass
      - vim
      - virtualenv
    update_cache: true
    state: present

- name: Add Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
    update_cache: true
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
