---
# https://github.com/trustedsec/ptf
- name: Clone The PenTesters Framework (PTF)
  ansible.builtin.git:
    repo: https://github.com/trustedsec/ptf
    dest: /opt/ptf

# https://sliver.sh
- name: Create Sliver Install directory
  ansible.builtin.file:
    path: /opt/sliver/
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Download Sliver Installer
  ansible.builtin.get_url:
    url: https://sliver.sh/install
    dest: /opt/sliver/install
    mode: '0755'

- name: Install Sliver
  ansible.builtin.command:
    cmd: ./install
    chdir: /opt/sliver
  register: sliver_install
  changed_when:
    - sliver_install.rc == 0
      or sliver_install.rc == 2

- name: Copy Sliver Update Script
  ansible.builtin.copy:
    src: update-sliver.py
    dest: /opt/sliver/
    mode: '0755'

- name: Install Sliver Armory Aliases & Extensions
  ansible.builtin.script:
    cmd: "update-sliver.py -u {{ github_user }} -t {{ github_token }}"
    chdir: /opt/sliver
  args:
    executable: python3

# https://github.com/SpecterOps/BloodHound
- name: Create Bloodhound Folder
  ansible.builtin.file:
    path: /opt/stacks/bloodhound
    state: directory

- name: Download Bloodhound Docker Compose file
  ansible.builtin.get_url:
    url: https://ghst.ly/getbhce
    dest: /opt/stacks/bloodhound/compose.yaml
    mode: '0664'
    owner: root
    group: users

- name: Adjust Bloodhound Docker Compose file
  ansible.builtin.lineinfile:
    path: /opt/stacks/bloodhound/compose.yaml
    regexp: '^version:.*'
    state: absent

- name: Start Bloodhound with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/bloodhound
    state: present

# https://github.com/c3c/ADExplorerSnapshot.py
- name: Clone ADExplorerSnapshot
  ansible.builtin.git:
    repo: https://github.com/c3c/ADExplorerSnapshot.py
    dest: /opt/ADExplorerSnapshot.py

- name: Make ADExplorerSnapshot VirtualEnv Directory
  ansible.builtin.file:
    path: /opt/ADExplorerSnapshot.py/venv
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Install ADExplorerSnapshot
  ansible.builtin.pip:
    name: file:///opt/ADExplorerSnapshot.py/
    virtualenv: /opt/ADExplorerSnapshot.py/venv
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: /usr/bin/python3
