---
- name: Clone The PenTesters Framework (PTF)
  ansible.builtin.git:
    repo: https://github.com/trustedsec/ptf
    dest: ~/opt/ptf

- name: Create Sliver Install directory
  ansible.builtin.file:
    path: ~/sliver
    mode: '0750'
    owner: root
    group: root
    state: directory

- name: Download Sliver Installer
  ansible.builtin.get_url:
    url: https://sliver.sh/install
    dest: ~/opt/sliver/install
    mode: '0755'

- name: Install Sliver
  ansible.builtin.command:
    cmd: ./install
    chdir: ~/opt/sliver

- name: Update Sliver
  ansible.builtin.command:
    cmd: sliver update

- name: Install Sliver Armory
  ansible.builtin.command:
    cmd: sliver armory install all

- name: Clone ADExplorerSnapshot
  ansible.builtin.git:
    repo: https://github.com/c3c/ADExplorerSnapshot.py
    dest: ~/opt/ADExplorerSnapshot.py

- name: Make ADExplorerSnapshot VirtualEnv
  ansible.builtin.file:
    path: /opt/ADExplorerSnapshot.py/venv
    mode: '0755'
    owner: root
    group: root

- name: Install ADExplorerSnapshot
  ansible.builtin.pip:
    requirements: ~/opt/ADExplorerSnapshot.py/requirements.txt
    virtualenv: /opt/ADExplorerSnapshot.py/venv

