---
- name: Install OS Dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gnupg
      - golang
      - mingw-w64
      - neovim
      - net-tools
      - python3-docker
      - python3-full
      - python3-jmespath
      - python3-libcloud
      - python3-pexpect
      - python3-pip
      - python3-venv
      - python3-winrm
      - sshpass
      - vim
      - virtualenv
    update_cache: true
    state: present

- name: Add Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
    update_cache: true
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create Container Folders
  ansible.builtin.file:
    path: "/opt/{{ item }}"
    state: directory
    mode: '0775'
    owner: root
    group: users
  loop:
    - dockge
    - stacks

# https://github.com/louislam/dockge
- name: Download Dockge Compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/louislam/dockge/master/compose.yaml
    dest: /opt/dockge/compose.yaml
    mode: '0664'
    owner: root
    group: users

- name: Adjust Dockge Docker Compose file
  ansible.builtin.lineinfile:
    path: /opt/dockge/compose.yaml
    regexp: '^version:.*'
    state: absent

- name: Start Dockge with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/dockge
    state: present
