---
- name: Install Above
  ansible.builtin.import_tasks:
    file: tools/above.yml
  tags:
    - all_tools
    - above

- name: Install ADExplorerSnapshot
  ansible.builtin.import_tasks: 
    file: tools/adexplorersnapshot.yml
  tags:
    - all_tools
    - adexplorersnapshot

- name: Install AD-Miner
  ansible.builtin.import_tasks: 
    file: tools/ad-miner.yml
  tags:
    - all_tools
    - ad-miner

- name: Install Bloodhound
  ansible.builtin.import_tasks: 
    file: tools/bloodhound.yml
  tags:
    - all_tools
    - bloodhound

- name: Install Sliver
  ansible.builtin.import_tasks: 
    file: tools/sliver.yml
  tags:
    - all_tools
    - sliver
