---
- name: Install Above
  ansible.builtin.import_tasks:
    file: tools/above.yml
  tags:
    - all_tools
    - above

- name: Install AD-Miner
  ansible.builtin.import_tasks: 
    file: tools/ad-miner.yml
  tags:
    - all_tools
    - ad-miner

- name: Install ADExplorerSnapshot
  ansible.builtin.import_tasks: 
    file: tools/adexplorersnapshot.yml
  tags:
    - all_tools
    - adexplorersnapshot

- name: Install ADSearch
  ansible.builtin.import_tasks:
    file: tools/adsearch.yml
  tags:
    - all_tools
    - adsearch

- name: Install AzureHound
  ansible.builtin.import_tasks:
    file: tools/azurehound.yml
  tags:
    - all_tools
    - azurehound

- name: Install Bloodhound
  ansible.builtin.import_tasks: 
    file: tools/bloodhound.yml
  tags:
    - all_tools
    - bloodhound

- name: Install BOFHound
  ansible.builtin.import_tasks:
    file: tools/bofhound.yml
  tags:
    - all_tools
    - bofhound

- name: Install Certipy
  ansible.builtin.import_tasks:
    file: tools/certipy.yml
  tags:
    - all_tools
    - certipy

- name: Install Corsy
  ansible.builtin.import_tasks:
    file: tools/corsy.yml
  tags:
    - all_tools
    - corsy

- name: Install CrackMapExec
  ansible.builtin.import_tasks:
    file: tools/crackmapexec.yml
  tags:
    - all_tools
    - crackmapexec

# Error on cargo build "could not compile `win32-error` due to 4 previous errors"
# - name: Install dll-spoofer-rs
#   ansible.builtin.import_tasks:
#     file: tools/dll-spoofer-rs.yml
#   tags:
#     - all_tools
#     - dll-spoofer-rs

- name: Install EDRSilencer
  ansible.builtin.import_tasks:
    file: tools/edrsilencer.yml
  tags:
    - all_tools
    - edrsilencer

- name: Install Ek47
  ansible.builtin.import_tasks:
    file: tools/ek47.yml
  tags:
    - all_tools
    - ek47

- name: Install enum4linux
  ansible.builtin.import_tasks:
    file: tools/enum4linux.yml
  tags:
    - all_tools
    - enum4linux

- name: Install enum4linux-ng
  ansible.builtin.import_tasks:
    file: tools/enum4linux-ng.yml
  tags:
    - all_tools
    - enum4linux-ng

- name: Install Exploit Database
  ansible.builtin.import_tasks:
    file: tools/exploitdb.yml
  tags:
    - all_tools
    - exploitdb

- name: Install Ferox Buster
  ansible.builtin.import_tasks:
    file: tools/feroxbuster.yml
  tags:
    - all_tools
    - feroxbuster

- name: Install Gitleaks
  ansible.builtin.import_tasks:
    file: tools/gitleaks.yml
  tags:
    - all_tools
    - gitleaks

- name: Install GoSigThief
  ansible.builtin.import_tasks:
    file: tools/gosigthief.yml
  tags:
    - all_tools
    - gosigthief

- name: Install HackTricks
  ansible.builtin.import_tasks:
    file: tools/hacktricks.yml
  tags:
    - all_tools
    - hacktricks

- name: Install Havoc
  ansible.builtin.import_tasks:
    file: tools/havoc.yml
  tags:
    - all_tools
    - havoc

- name: Install havoc_profile_generator
  ansible.builtin.import_tasks:
    file: tools/havoc_profile_generator.yml
  tags:
    - all_tools
    - havoc_profile_generator

- name: Install Sliver
  ansible.builtin.import_tasks: 
    file: tools/sliver.yml
  tags:
    - all_tools
    - sliver
