---
- name: Include Vaulted Variables
  ansible.builtin.include_vars:
    file: vault.yml
  tags:
    - always

- name: Prelim Tasks
  ansible.builtin.import_tasks:
    file: prelim.yml
  # tags:
  #   - always

- name: Install Dependencies
  ansible.builtin.import_tasks:
    file: install_deps.yml
  # tags:
  #   - always

- name: Install Tools
  ansible.builtin.import_tasks:
    file: install_tools.yml

- name: Create Tool Aliases
  ansible.builtin.import_tasks:
    file: create_aliases.yml
  tags:
    - always
