---
- name: Identify System Users
  ansible.builtin.find:
    paths: /home
    recurse: no
    file_type: directory
  register: users

- name: Create Users .config Directory
  ansible.builtin.file:
    dest: '{{ item.path }}/.config'
    mode: '0700'
    owner: '{{ item.pw_name }}'
    group: '{{ item.gr_name }}'
    state: directory
  loop: '{{ users.files }}'

- name: Configure User Power Management Settings
  ansible.builtin.copy:
    src: powermanagementprofilesrc
    dest: '{{ item.path }}/.config/powermanagementprofilesrc'
    mode: '0600'
    owner: '{{ item.pw_name }}'
    group: '{{ item.gr_name }}'
  loop: '{{ users.files }}'

- name: Install OS Dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gnupg
      - golang
      - neovim
      - net-tools
      - python3-jmespath
      - python3-libcloud
      - python3-pexpect
      - python3-pip
      - python3-venv
      - python3-winrm
      - sshpass
      - vim
      - virtualenv
    update_cache: true
    state: present

- name: Add Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
    update_cache: true
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Clone The PenTesters Framework (PTF)
  ansible.builtin.git:
    repo: https://github.com/trustedsec/ptf
    dest: ~/ptf

- name: Create Sliver Install directory
  ansible.builtin.file:
    path: ~/sliver
    mode: '0750'
    owner: root
    group: root
    state: directory

- name: Download Sliver Installer
  ansible.builtin.get_url:
    url: https://sliver.sh/install
    dest: ~/sliver/install
    mode: '0755'

- name: Install Sliver
  ansible.builtin.command:
    cmd: ./install
    chdir: ~/sliver
