---
- name: Identify System Users
  ansible.builtin.find:
    paths: /home
    recurse: no
    file_type: directory
  register: users

- name: Create Users .config Directory
  ansible.builtin.file:
    dest: '{{ item.path }}/.config'
    mode: '0700'
    owner: '{{ item.pw_name }}'
    group: '{{ item.gr_name }}'
    state: directory
  loop: '{{ users.files }}'

- name: Configure User Power Management Settings
  ansible.builtin.copy:
    src: powermanagementprofilesrc
    dest: '{{ item.path }}/.config/powermanagementprofilesrc'
    mode: '0600'
    owner: '{{ item.pw_name }}'
    group: '{{ item.gr_name }}'
  loop: '{{ users.files }}'
