---
# https://github.com/c3c/ADExplorerSnapshot.py
- name: Clone ADExplorerSnapshot
  ansible.builtin.git:
    repo: https://github.com/c3c/ADExplorerSnapshot.py
    dest: /opt/ADExplorerSnapshot.py

- name: Make ADExplorerSnapshot VirtualEnv Directory
  ansible.builtin.file:
    path: /opt/ADExplorerSnapshot.py/venv
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Install ADExplorerSnapshot
  ansible.builtin.pip:
    name: file:///opt/ADExplorerSnapshot.py/
    virtualenv: /opt/ADExplorerSnapshot.py/venv
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: /usr/bin/python3
