---
# https://github.com/SpecterOps/BloodHound
- name: Create Bloodhound Folder
  ansible.builtin.file:
    path: /opt/stacks/bloodhound
    state: directory

- name: Download Bloodhound Docker Compose file
  ansible.builtin.get_url:
    url: https://ghst.ly/getbhce
    dest: /opt/stacks/bloodhound/compose.yaml
    mode: '0664'
    owner: root
    group: users

- name: Adjust Bloodhound Docker Compose file
  ansible.builtin.lineinfile:
    path: /opt/stacks/bloodhound/compose.yaml
    regexp: '^version:.*'
    state: absent

- name: Start Bloodhound with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/bloodhound
    state: present
