---
# https://github.com/cddmp/enum4linux-ng
- name: Clone enum4linux-ng
  ansible.builtin.git:
    repo: https://github.com/cddmp/enum4linux-ng
    dest: /opt/enum4linux-ng

- name: Make enum4linux-ng VirtualEnv Directory
  ansible.builtin.file:
    path: /opt/enum4linux-ng/venv
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Install enum4linux-ng
  ansible.builtin.pip:
    name: file:///opt/enum4linux-ng/
    virtualenv: /opt/enum4linux-ng/venv
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: /usr/bin/python3
