---
# https://github.com/epi052/feroxbuster
- name: Create Ferox Buster Folder
  ansible.builtin.file:
    path: /opt/feroxbuster
    state: directory

- name: Download Ferox Buster Installation file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh
    dest: /opt/feroxbuster/install-nix.sh
    mode: '0554'
    owner: root
    group: users

- name: Install Ferox Buster
  ansible.builtin.command:
    cmd: ./install-nix.sh
    chdir: /opt/feroxbuster