---
# https://github.com/HackTricks-wiki/hacktricks
- name: Clone HackTricks Wiki
  ansible.builtin.git:
    repo: https://github.com/HackTricks-wiki/hacktricks
    dest: /opt/hacktricks

# https://github.com/HackTricks-wiki/hacktricks-cloud
- name: Clone HackTricks Cloud Wiki
  ansible.builtin.git:
    repo: https://github.com/HackTricks-wiki/hacktricks-cloud
    dest: /opt/hacktricks-cloud
