---
# https://github.com/0xv1n/Havoc-ProfileGenerator
- name: Clone Havoc-ProfileGenerator
  ansible.builtin.git:
    repo: https://github.com/0xv1n/Havoc-ProfileGenerator
    dest: /opt/Havoc-ProfileGenerator

- name: Start Havoc-ProfileGenerator for the first time
  ansible.builtin.shell:
    cmd: 'go run main.go &'
    chdir: /opt/Havoc-ProfileGenerator
