---
# https://github.com/HavocFramework/Havoc
- name: Clone Havoc
  ansible.builtin.git:
    repo: https://github.com/HavocFramework/Havoc
    dest: /opt/havoc

- name: Install Build Dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - golang-go
      - qtbase5-dev
      - libqt5websockets5-dev
      - python3-dev
      - libboost-all-dev
      - mingw-w64
      - nasm
    state: present

- name: Install Go Build Dependencies
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: /opt/havoc/teamserver
  loop:
    - go mod download golang.org/x/sys
    - go mod download github.com/ugorji/go

- name: Build Havoc TeamServer
  ansible.builtin.command:
    cmd: make ts-build
    chdir: /opt/havoc

- name: Build Havoc Client
  ansible.builtin.command:
    cmd: make client-build
    chdir: /opt/havoc