---
# https://github.com/HavocFramework/Havoc
- name: Clone Havoc
  ansible.builtin.git:
    repo: https://github.com/HavocFramework/Havoc
    dest: /opt/havoc

- name: Install Go Build Dependencies
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: /opt/havoc/teamserver
  loop:
    - go mod download golang.org/x/sys
    - go mod download github.com/ugorji/go

- name: Build Havoc TeamServer
  ansible.builtin.command:
    cmd: make ts-build
    chdir: /opt/havoc

- name: Build Havoc Client
  ansible.builtin.command:
    cmd: make client-build
    chdir: /opt/havoc