---
# https://github.com/klezVirus/inceptor
- name: Clone inceptor
  ansible.builtin.git:
    repo: https://github.com/klezVirus/inceptor
    dest: /opt/inceptor

- name: Make inceptor VirtualEnv Directory
  ansible.builtin.file:
    path: /opt/inceptor/venv
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Install inceptor requirements
  ansible.builtin.pip:
    requirements: /opt/inceptor/requirements.txt
    virtualenv: /opt/inceptor/venv
    virtualenv_command: /usr/bin/virtualenv
    virtualenv_python: /usr/bin/python3
