---
# https://github.com/trustedsec/ptf
- name: Clone The PenTesters Framework (PTF)
  ansible.builtin.git:
    repo: https://github.com/trustedsec/ptf
    dest: /opt/ptf

# https://sliver.sh
- name: Create Sliver Install directory
  ansible.builtin.file:
    path: /opt/sliver/
    mode: '0775'
    owner: root
    group: users
    state: directory

- name: Download Sliver Installer
  ansible.builtin.get_url:
    url: https://sliver.sh/install
    dest: /opt/sliver/install
    mode: '0755'

- name: Install Sliver
  ansible.builtin.command:
    cmd: ./install
    chdir: /opt/sliver
  register: sliver_install
  changed_when:
    - sliver_install.rc == 0
      or sliver_install.rc == 2

- name: Copy Sliver Update Script
  ansible.builtin.copy:
    src: update-sliver.py
    dest: /opt/sliver/
    mode: '0755'

- name: Install Sliver Armory Aliases & Extensions
  ansible.builtin.script:
    cmd: "update-sliver.py -u {{ github_user }} -t {{ github_token }}"
    chdir: /opt/sliver
  args:
    executable: python3
